from tuiles.tuileterrain import TuileTerrain
from tuiles.tuileeau import TuileEau
from tuiles.tuilefeu import TuileFeu
from tuiles.tuilemur import TuileMur
from tuiles.tuilesable import TuileSable
from tuiles.tuileteleport import TuileTéléport
from tuiles.tuilelevier import TuileLevier
from tuiles.tuilerude import TuileRude
from tuiles.tuilebascule import TuileBascule
from tuiles.tuileglace import TuileGlace
from tuiles.tuilecoffre import TuileCoffre
